package br.com.caelum.estoque.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2019-04-29T17:54:00.446-03:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://ws.estoque.caelum.com.br/", name = "EstoqueWS")
@XmlSeeAlso({ObjectFactory.class})
public interface EstoqueWS {

    @WebMethod
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/listAllItemsRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/listAllItemsResponse")
    @RequestWrapper(localName = "listAllItems", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.ListAllItems")
    @ResponseWrapper(localName = "listAllItemsResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.ListAllItemsResponse")
    @WebResult(name = "Items", targetNamespace = "")
    public br.com.caelum.estoque.ws.ListaItens listAllItems();

    @WebMethod
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItemRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItemResponse", fault = {@FaultAction(className = AuthorizationException.class, value = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItem/Fault/AuthorizationException")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "cadastrarItemResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "result")
    public CadastrarItemResponse cadastrarItem(
        @WebParam(partName = "parameters", name = "cadastrarItem", targetNamespace = "http://ws.estoque.caelum.com.br/")
        CadastrarItem parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://ws.estoque.caelum.com.br/", header = true)
        TokenUsuario token
    ) throws AuthorizationException;

    @WebMethod
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/listItemsRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/listItemsResponse")
    @RequestWrapper(localName = "listItems", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.ListItems")
    @ResponseWrapper(localName = "listItemsResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.ListItemsResponse")
    @WebResult(name = "Items", targetNamespace = "")
    public br.com.caelum.estoque.ws.ListaItens listItems(
        @WebParam(name = "arg0", targetNamespace = "")
        br.com.caelum.estoque.ws.Filtros arg0
    );
}
