
package br.com.caelum.estoque.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstoqueWS", targetNamespace = "http://ws.estoque.caelum.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstoqueWS {


    /**
     * 
     * @return
     *     returns br.com.caelum.estoque.client.ListaItens
     */
    @WebMethod(action = "http://ws.estoque.caelum.com.br/EstoqueWS/listAllItemsRequest")
    @WebResult(name = "Items", targetNamespace = "")
    @RequestWrapper(localName = "listAllItems", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.client.ListAllItems")
    @ResponseWrapper(localName = "listAllItemsResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.client.ListAllItemsResponse")
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/listAllItemsRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/listAllItemsResponse")
    public ListaItens listAllItems();

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns br.com.caelum.estoque.client.CadastrarItemResponse
     * @throws AuthorizationException
     */
    @WebMethod(action = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItemRequest")
    @WebResult(name = "cadastrarItemResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItemRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItemResponse", fault = {
        @FaultAction(className = AuthorizationException.class, value = "http://ws.estoque.caelum.com.br/EstoqueWS/cadastrarItem/Fault/AuthorizationException")
    })
    public CadastrarItemResponse cadastrarItem(
        @WebParam(name = "cadastrarItem", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "parameters")
        CadastrarItem parameters,
        @WebParam(name = "token", targetNamespace = "http://ws.estoque.caelum.com.br/", header = true, partName = "token")
        TokenUsuario token)
        throws AuthorizationException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.caelum.estoque.client.ListaItens
     */
    @WebMethod(action = "http://ws.estoque.caelum.com.br/EstoqueWS/listItemsRequest")
    @WebResult(name = "Items", targetNamespace = "")
    @RequestWrapper(localName = "listItems", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.client.ListItems")
    @ResponseWrapper(localName = "listItemsResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.client.ListItemsResponse")
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/listItemsRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/listItemsResponse")
    public ListaItens listItems(
        @WebParam(name = "arg0", targetNamespace = "")
        Filtros arg0);

}
